[package]
name = "snowscape"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.14.0-dev"
iced_anim = { git = "https://github.com/bradysimon/iced_anim", branch = "iced/master" }

[workspace]
members = ["examples/demo"]

[workspace.dependencies]
iced = "0.14.0-dev"

[patch.crates-io]
iced.git = "https://github.com/iced-rs/iced.git"
iced.branch = "master"
