[package]
name = "snowscape"
description = "A framework for previewing Iced components"
version = "0.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/bradysimon/snowscape"
readme = "README.md"
