[package]
name = "dynamic_params"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
snowscape = { path = "../.." }
iced.workspace = true

[lib]
name = "dynamic_params"
path = "src/lib.rs"
