[package]
name = "demo"
version = "0.1.0"
edition = "2024"
publish = false
default-run = "demo"

[lib]
name = "demo"
path = "src/lib.rs"

[dependencies]
snowscape = { path = "../.." }
iced.workspace = true

[[bin]]
name = "demo"
path = "src/main.rs"

[[bin]]
name = "preview"
path = "src/preview.rs"